trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- task: PowerShell@2
  displayName: Update file in GIT repository
  inputs:
    targetType: 'inline'
    script: |
      # User email and name must be set to be able to commit.
      git config user.email "$(Build.RequestedForEmail)"
      git config user.name "$(Build.RequestedFor)"

      # Workspace is not on a branch by default.
      git fetch
      git checkout main

      $timeStamp = Get-Date -AsUTC -Format "yyyy-MM-ddTHH:mm:ssZ"
      $logEntry = "${timeStamp}: $(Build.BuildId), $(Build.BuildNumber), $(Build.Reason), $(Build.SourceBranch), $(Build.SourceVersion)"
      $logEntry | Out-File -Append -FilePath log.txt

      git add log.txt
      git commit -m "Update log" -m "[skip ci]"
      git push
    pwsh: true
    workingDirectory: $(Build.SourcesDirectory)
