trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- task: PowerShell@2
  displayName: Update file in GIT repository
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "RequestedForEmail: $(Build.RequestedForEmail)"
      Write-Host "RequestedForId: $(Build.RequestedForId)"
      Write-Host "RequestedFor: $(Build.RequestedFor)"
      Write-Host "QueuedById: $(Build.QueuedById)"
      Write-Host "QueuedBy: $(Build.QueuedBy)"
      $timeStamp = Get-Date -AsUTC -Format "yyyy-MM-ddTHH:mm:ssZ"
      $logEntry = "${timeStamp}: $(Build.BuildId), $(Build.Reason), $(Build.SourceBranch), $(Build.SourceVersion)"
      Write-Host "timeStamp: $timeStamp"
      Write-Host "logEntry: $logEntry"
      # $logEntry | Out-File -Append -FilePath log.txt
      # git add log.txt
      # git commit -m "Update log" -m "[skip ci]"
      # git push
    pwsh: true
    workingDirectory: $(Build.SourcesDirectory)
